package kludwisz.ancientcity.structures;

import java.util.List;

public class AncientCityPieceNames {
	public static final List<String> PIECENAMES = List.of(
			"city/entrance/entrance_connector",
			"city/entrance/entrance_path_1",
			"city/entrance/entrance_path_2",
			"city/entrance/entrance_path_3",
			"city/entrance/entrance_path_4",
			"city/entrance/entrance_path_5",
			"city_center/city_center_1",
			"city_center/city_center_2",
			"city_center/city_center_3",
			"city_center/walls/bottom_1",
			"city_center/walls/bottom_2",
			"city_center/walls/bottom_left_corner",
			"city_center/walls/bottom_right_corner",
			"city_center/walls/bottom_right_corner_1",
			"city_center/walls/bottom_right_corner_2",
			"city_center/walls/left",
			"city_center/walls/right",
			"city_center/walls/top",
			"city_center/walls/top_left_corner",
			"city_center/walls/top_right_corner",
			"structures/barracks",
			"structures/camp_1",
			"structures/camp_2",
			"structures/camp_3",
			"structures/chamber_1",
			"structures/chamber_2",
			"structures/chamber_3",
			"structures/ice_box_1",
			"structures/large_pillar_1",
			"structures/large_ruin_1",
			"structures/medium_pillar_1",
			"structures/medium_ruin_1",
			"structures/medium_ruin_2",
			"structures/sauna_1", // 33
			"structures/small_ruin_1",
			"structures/small_ruin_2",
			"structures/small_statue",
			"structures/tall_ruin_1",
			"structures/tall_ruin_2",
			"structures/tall_ruin_3",
			"structures/tall_ruin_4",
			"walls/intact_corner_wall_1",
			"walls/intact_horizontal_wall_1",
			"walls/intact_horizontal_wall_2",
			"walls/intact_horizontal_wall_bridge",
			"walls/intact_horizontal_wall_passage_1",
			"walls/intact_horizontal_wall_stairs_1",
			"walls/intact_horizontal_wall_stairs_2",
			"walls/intact_horizontal_wall_stairs_3",
			"walls/intact_horizontal_wall_stairs_4",
			"walls/intact_horizontal_wall_stairs_5",
			"walls/intact_intersection_wall_1",
			"walls/intact_lshape_wall_1",
			"walls/ruined_corner_wall_1",
			"walls/ruined_corner_wall_2",
			"walls/ruined_horizontal_wall_stairs_1",
			"walls/ruined_horizontal_wall_stairs_2",
			"walls/ruined_horizontal_wall_stairs_3",
			"walls/ruined_horizontal_wall_stairs_4",
			"sculk_patch", 
			"empty"	// index = 60
	);
}
